### ISSUE TITLE
[功能]请求为浏览器插件添加一键下载功能

### ISSUE THREAD

**Issue by DoudouMee** [zpqsunny/Transmission-Web-UI#1]
请求开发者为浏览器扩展添加 磁力链接一键下载的功能

类似右键下载或者点击扩展识别当前页磁力进行下载这种

**Comment by zpqsunny** [comment]
我进行了尝试
在chrome扩展中chrome.storage.local 方法无法获取到Vue 编译后的单页面里的localStorage数据
故无法实现

**Comment by zpqsunny** [comment]
已增加此功能,需要界面退出重新登录即可 版本号 >= v2.0.5
1. 选中长度为40的 **Hash** 字符串可以点击右键下载
2. **url**链接点击右键下载

优先级: **选中** > **链接**
可能存在的问题

1. 如果出现无法快速下载,请先进入主页面看工作是否正常/退出重新进入
