### ISSUE TITLE
可以实现自动添加tracker 到新下载吗

### ISSUE THREAD

**Issue by ALILEX-1** [zpqsunny/Transmission-Web-UI#4]
类似qb

**Comment by zpqsunny** [comment]
Transmission 上没有对应的api接口, 只能手动添加, 再想方便点也只能做到一键添加...

**Comment by ALILEX-1** [comment]
嗯，类似右键增加一个选项（一键添加）

**Comment by zpqsunny** [comment]
transmission 4.0版本 增加了默认tracker配置项，新版插件已更新配置
