### ISSUE TITLE
Transmission RPC version must >= 16

### ISSUE THREAD

**Issue by lesca** [zpqsunny/Transmission-Web-UI#5]
今天断开连接后重新连接就连不上了：
`Transmission RPC version must >= 16`

用TR-GUI连接没问题。
之前用的好好的，有没有解决方法？

**Comment by zpqsunny** [comment]
这个提示是指transmission版本小于3.0了,之前没有做版本校验,现在有版本校验了,最低版本要求是3.0,可以手动查看下版本,升级到3.0即可.

**Comment by lesca** [comment]
升级了 transmission 就好了。谢谢
